schema_version: 1

context:
  version: "3.1.10"

package:
  name: libmodbus
  version: ${{ version }}

source:
  url: https://github.com/stephane/libmodbus/releases/download/v${{ version }}/libmodbus-${{ version }}.tar.gz
  sha256: 899be4e25ab7fe5799d43f9567510d6f063d2e8f56136dd726b6fd976f9b2253

build:
  number: 0
  script: build.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - make
  host:
    - libgcc-ng
  run:
    - libgcc-ng

tests:
  - script:
      - test -f $PREFIX/include/modbus/modbus.h
      - pkg-config --modversion libmodbus
    requirements:
      run:
        - pkg-config

about:
  homepage: https://libmodbus.org
  license: LGPL-2.1-or-later
  license_file: COPYING.LESSER
  summary: A Modbus library for Linux, Mac OS, FreeBSD and Windows
  repository: https://github.com/stephane/libmodbus
