schema_version: 1

context:
  version: "8.2.5"

package:
  name: ros-jazzy-tracetools-trace
  version: ${{ version }}

source:
  url: https://github.com/ros2/ros2_tracing/archive/refs/tags/${{ version }}.tar.gz
  sha256: 17061d5925ee8d97c540058736893887c733d9c4dbf64f4b2d9c09d9054bdafa

build:
  number: 0
  noarch: python
  script: build.sh

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - procps-ng

tests:
  - package_contents:
      files:
        - site-packages/tracetools_trace/__init__.py
        - share/tracetools_trace/package.xml
        - bin/trace

about:
  homepage: https://github.com/ros2/ros2_tracing
  license: Apache-2.0
  summary: Tools for setting up tracing sessions
  repository: https://github.com/ros2/ros2_tracing
